apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "brokencrystals.fullname" . }}-keycloak-postgres
  namespace: {{ .Release.Namespace }}
data:
  postgresql.conf.sample: |
    listen_addresses = '*'
    port = 5433
